blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Community Support
    url: https://github.com/tensorflow/model-card-toolkit/discussions/categories/q-a
    about: Ask the community for help
  - name: ğŸ’¡ Feature Requests
    url: https://github.com/tensorflow/model-card-toolkit/discussions/categories/ideas
    about: Share ideas for new features
