name: Lint

on:
  pull_request:
    paths:
      - '**.py'
      - '.github/ci/**'
      - '.github/workflows/lint.yml'
    branches:
      - master
      - r*
    tags:
      - v*

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - uses: pre-commit/action@v2.0.3
      name: Run pre-commit checks (pylint/yapf/isort)
      env:
        SKIP: insert-license
      with:
        extra_args: --hook-stage push --all-files
